Repository bSI-InfraRoom/IFC-Specification, pull requests merged in 2022-07, with the labels that each got.

#406 Define and assign PSET MATERIALDRIVEN and PSET PROFILEDRIVEN issue 110
  IFC4x3/Constants/p/PSET_MATERIALDRIVEN_3fKFY21Sr2w8m4BgoeCfJI.xml
  IFC4x3/Constants/p/PSET_PROFILEDRIVEN_1jubIKLYf7yuJfebXJ7ETa.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcKernel/Types/IfcPropertySetTemplateTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialCombustion/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialCommon/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialConcrete/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialEnergy/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialFuel/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialHygroscopic/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialMechanical/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialOptical/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialSteel/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialThermal/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialWater/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialWood/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialWoodBasedBeam/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMaterialResource/PropertySets/Pset_MaterialWoodBasedPanel/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcProfileResource/PropertySets/Pset_ProfileArbitraryDoubleT/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcProfileResource/PropertySets/Pset_ProfileArbitraryHollowCore/DocPropertySet.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcProfileResource/PropertySets/Pset_ProfileMechanical/DocPropertySet.xml
Labels: EXPRESS, properties

#413 RAILWAYTRACK and RAILWAYLINE + pset association issue 305
  IFC4x3/Constants/r/RAILWAYLINE_0EI3QpV6rCqe7ljBV9Ekx8.xml
  IFC4x3/Constants/r/RAILWAYTRACK_2DycPctdT8NA$DjgQd0dgt.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcBuiltSystemTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/PropertySets/Pset_BuiltSystemRailwayLine/DocPropertySet.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/PropertySets/Pset_BuiltSystemRailwayLine/Documentation.md
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/PropertySets/Pset_BuiltSystemRailwayTrack/DocPropertySet.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/PropertySets/Pset_BuiltSystemRailwayTrack/Documentation.md
Labels: EXPRESS, properties

#417 Adding attribute `IfcDerivedUnit.Name` and enums `FILLER` and `FLASHING` to `IfcDiscreteAccessoryTypeEnum`
  IFC4x3/Constants/f/FILLER_2yUKyb8RD0ZwgSrzMvR8e0.xml
  IFC4x3/Constants/f/FLASHING_0rTlsBNtnBch09iiRWLrZ1.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMeasureResource/Entities/IfcDerivedUnit/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcMeasureResource/Types/IfcLabel/DocDefined.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedComponentElements/Types/IfcDiscreteAccessoryTypeEnum/DocEnumeration.xml
Labels: EXPRESS

#418 Remove elemented and standard cases issue 53
  IFC4x3/ModelViews/Design Transfer View/DocModelView.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcOpeningElement/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcOpeningStandardCase/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcOpeningStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcBeam/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcBeamStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcBeamStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcColumn/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcColumnStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcColumnStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcDoor/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcDoorStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcDoorStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcMember/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcMemberStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcMemberStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcPlate/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcPlateStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcPlateStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcSlab/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcSlabElementedCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcSlabElementedCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcSlabStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcSlabStandardCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWall/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWallElementedCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWallElementedCase/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWindow/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWindowStandardCase/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWindowStandardCase/Documentation.md
Labels: EXPRESS

#436 ElevationOfSSLRelative and FFL issue 36
  IFC4x3/Properties/e/ElevationOfFFLRelative_3p$gHe8S590Q5xZmxUuMwH/DocProperty.xml
  IFC4x3/Properties/e/ElevationOfFFLRelative_3p$gHe8S590Q5xZmxUuMwH/Documentation.md
  IFC4x3/Properties/e/ElevationOfSSLRelative_3x5PSsV1TCdAdeFviYo34j/DocProperty.xml
  IFC4x3/Properties/e/ElevationOfSSLRelative_3x5PSsV1TCdAdeFviYo34j/Documentation.md
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/PropertySets/Pset_BuildingStoreyCommon/DocPropertySet.xml
Labels: properties

#374 Addressing IfcTaskTypeEnum changes on bsi repo
  IFC4x3/Constants/a/ADJUSTMENT_2oGpmaKh5CFeOjolEUEWef.xml
  IFC4x3/Constants/c/CALIBRATION_2Rvgx6TsL9oQf7$9O5TxXe.xml
  IFC4x3/Constants/e/EMERGENCY_3a4XUgw8b7JQ4bwWmmls_8.xml
  IFC4x3/Constants/i/INSPECTION_0Q1dK2l959G81GZlPTWPTg.xml
  IFC4x3/Constants/m/MAINTENANCE_0_cwhoroLCy9HjJ6b6y82v.xml
  IFC4x3/Constants/s/SAFETY_0DxYyoL516YhpXBLtMD4K3.xml
  IFC4x3/Constants/s/SHUTDOWN_16z6Ixvyr28Ol8bpgEVVVk.xml
  IFC4x3/Constants/s/STARTUP_2nUVxWrHfCDfEXoVBS1R8g.xml
  IFC4x3/Constants/t/TESTING_12OPd4O_z8dPYmt3JdiBSI.xml
  IFC4x3/Constants/t/TROUBLESHOOTING_04giICEgXAF8iV6_NVmtF$.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProcessExtension/Types/IfcTaskTypeEnum/DocEnumeration.xml
Labels: EXPRESS

#452 align to X3D and glTF add PHYSICAL reflectance model
  IFC4x3/Constants/p/PHYSICAL_3rVo10F0D2585PrGK5AU0K.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcPresentationAppearanceResource/Types/IfcReflectanceMethodEnum/DocEnumeration.xml
Labels: EXPRESS

#429 Adding JET PDT for IfcFan
  IFC4x3/Constants/j/JET_3wLS6pgl56bPAi_EgGuchA.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcHvacDomain/Types/IfcFanTypeEnum/DocEnumeration.xml
Labels: EXPRESS, IFC Tunnel
