Repository bSI-InfraRoom/IFC-Specification, pull requests merged in 2024-06, with the labels that each got.

#809 making all NumberOfVoxels mandatory
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
Labels: EXPRESS

#805 Fix/vector voxel data
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/DocSchema.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcIntegerVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcLabelVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcLogicalVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcRealVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcVectorVoxelData/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
Labels: EXPRESS

#808 Reconcile/ifc point dim
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcCartesianPoint/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcPoint/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcPointByDistanceExpression/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcPointOnCurve/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcPointOnSurface/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcPointDim/DocFunction.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcPointDim/Documentation.md
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcPointDim/Expression.txt
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Types/IfcCurveMeasureSelect/DocSelect.xml
Labels: EXPRESS

#813 remove CorrectStyleAssigned on door and window
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcDoor/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcWindow/DocEntity.xml
Labels: EXPRESS

#819 reconcile IfcTransportationDeviceType base type
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcTransportElementType/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcTransportationDeviceType/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcVehicleType/DocEntity.xml
Labels: EXPRESS

#569 Pset_LateralExcavationCommon
  IFC4x3/Properties/r/RadialExcavationDepth_1hc8WY5vP3gg1foxh3ure3/DocProperty.xml
  IFC4x3/Properties/r/RadialExcavationDepth_1hc8WY5vP3gg1foxh3ure3/Documentation.md
  IFC4x3/Properties/r/RadialExcavationDirection_0PWybQDsb7VuLXarptQq0N/DocProperty.xml
  IFC4x3/Properties/r/RadialExcavationDirection_0PWybQDsb7VuLXarptQq0N/Documentation.md
  IFC4x3/Properties/r/RadialExcavationTypeOther_3RsgMwbTP2khfQXrle7GMJ/DocProperty.xml
  IFC4x3/Properties/r/RadialExcavationTypeOther_3RsgMwbTP2khfQXrle7GMJ/Documentation.md
  IFC4x3/Properties/r/RadialExcavationType_36CrYf_abBQQiXtlkMLup4/DocProperty.xml
  IFC4x3/Properties/r/RadialExcavationType_36CrYf_abBQQiXtlkMLup4/Documentation.md
  IFC4x3/PropertyConstants/l/LATERAL_1Jji0xIazBs9WOFFvKU1Tg.xml
  IFC4x3/PropertyConstants/n/NICHE_2WbOSaWs5FmQtEchh1Y$E7.xml
  IFC4x3/PropertyConstants/o/OTHER_3vjLqXCBDFif_m_$q46G$N.xml
  IFC4x3/PropertyConstants/p/PROFILEENLARGEMENT_0nsScLj3XF9vOyG8r0UCj6.xml
  IFC4x3/PropertyConstants/r/RADIAL_1ybalYR9j4o9wByM$rNG8U.xml
  IFC4x3/PropertyConstants/r/REPROFILING_0$GSD3AIzCcfqtlJ83qghf.xml
  IFC4x3/PropertyConstants/v/VERTICAL_1ksLZ5eOX7ahYXQyWZcmYq.xml
  IFC4x3/PropertyEnumerations/r/PEnum_RadialExcavationDirection.xml
  IFC4x3/PropertyEnumerations/r/PEnum_RadialExcavationType.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_LateralExcavationCommon/DocPropertySet.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_LateralExcavationCommon/Documentation.md
Labels: IFC Tunnel, properties, BucketB

#723 Split IfcImprovedGround.GROUTED into INJECTIONGROUTED and JETGROUTED
  IFC4x3/Constants/i/INJECTIONGROUTED_3h7yaBv192owNn0lteQF65.xml
  IFC4x3/Constants/j/JETGROUTED_0fQxW2iV14EvWNunKjOkQT.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcImprovedGroundTypeEnum/DocEnumeration.xml
Labels: EXPRESS, IFC Tunnel, BucketB

#827 EX-GU-IfcReinforcingMeshTypeEnum.STEELSTRAPS + PSet_ReinforcingMeshTy…
  IFC4x3/Constants/s/STEELSTRAPS_3tBxsQu7XEn9Ysh_1vBFSC.xml
  IFC4x3/Properties/b/BoltLength_3qco31$wb0lR1QsW$CJbYv/DocProperty.xml
  IFC4x3/Properties/b/BoltLength_3qco31$wb0lR1QsW$CJbYv/Documentation.md
  IFC4x3/Properties/b/BoltType_1hXaGNY9PBI8lNN9k3njm_/DocProperty.xml
  IFC4x3/Properties/b/BoltType_1hXaGNY9PBI8lNN9k3njm_/Documentation.md
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralElementsDomain/PropertySets/Pset_ReinforcingMeshTypeSteelStraps/DocPropertySet.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralElementsDomain/PropertySets/Pset_ReinforcingMeshTypeSteelStraps/Documentation.md
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralElementsDomain/Types/IfcReinforcingMeshTypeEnum/DocEnumeration.xml
Labels: EXPRESS, IFC Tunnel, properties, BucketB

#838 remove non existent curve type check for IfcCurveSegment2D
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcCurveDim/Expression.txt
Labels: EXPRESS

#839 correct IfcBooleanClippingResult.FirstOperandType typo for correct ty…
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcBooleanClippingResult/DocEntity.xml
Labels: EXPRESS

#840 Reconcile IfcSimplePropertyTemplateTypeEnum
  IFC4x3/Constants/q/Q_NUMBER_2hLEoN2EnBMA8E$bOBCgi1.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcKernel/Types/IfcSimplePropertyTemplateTypeEnum/DocEnumeration.xml
Labels: EXPRESS, reconcile

#835 reconcile IfcGradient function
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Entities/IfcGradientCurve/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcGradient/DocFunction.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcGradient/Expression.txt
Labels: EXPRESS

#703 Added subtypes to IfcUndergroundExcavation
  IFC4x3/Constants/c/CROSSCONNECTION_0HBMcuwpX2gedg0EWh55Yh.xml
  IFC4x3/Constants/f/FACEEXCAVATION_0OQz8Pf7r36AHB8zu64Byl.xml
  IFC4x3/Constants/f/FULLFACE_23hNQtT7jEW82RLnkEK5XW.xml
  IFC4x3/Constants/n/NICHE_2DfGP2dxf4Pec3oetqqoRR.xml
  IFC4x3/Constants/p/PILOTBORE_3X$C6tqFDC18JFwxqWADss.xml
  IFC4x3/Constants/p/PROFILEENLARGEMENT_0AqxHr_ALAV930uuRJmsUs.xml
  IFC4x3/Constants/r/RADIALEXCAVATION_2AjeCMJjP8tf9O2_kG2k9A.xml
  IFC4x3/Constants/r/REAMING_25nAeQUED8oBK_$O5qdDb8.xml
  IFC4x3/Constants/r/REPROFILING_3UB_3hCW1AVBD6ro7Pms_u.xml
  IFC4x3/Constants/s/SHAFT_3cR6ZIeV9FPRBSrtu7P$Gi.xml
  IFC4x3/Constants/s/STAGED_0G1o0dTaP2yQpif$L24MRg.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcFaceExcavation/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcFaceExcavation/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcRadialExcavation/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcRadialExcavation/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcUndergroundExcavation/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcFaceExcavationTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcFaceExcavationTypeEnum/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcRadialExcavationTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcRadialExcavationTypeEnum/Documentation.md
Labels: EXPRESS, IFC Tunnel, BucketB

#845 Reintroduce and deprecate IfcReinforcedSoil/IfcReinforcedSoilTypeEnum
  IFC4x3/Constants/g/GROUTED_360hLDtPD90BYLYclHu1Gh.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcRepresentationResource/Types/IfcWellKnownTextLiteral/DocDefined.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcReinforcedSoil/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcReinforcedSoil/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcGeotechnicalStratumTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcGeotechnicalStratumTypeEnum/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcReinforcedSoilTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcReinforcedSoilTypeEnum/Documentation.md
Labels: EXPRESS, IFC Tunnel, reconcile

#678 EXC-GI_Pset_ImprovedGroundTypeDewatered plus enum IfcImprovedGroundTypeEnum.DEWATERED
  IFC4x3/Constants/d/DEWATERED_1BDq2sVVj5w9uDrfSeaMBh.xml
  IFC4x3/Properties/a/AverageBoreholeDepth_3NM6PipTTFyvqSdj8magOF/DocProperty.xml
  IFC4x3/Properties/a/AverageBoreholeDepth_3NM6PipTTFyvqSdj8magOF/Documentation.md
  IFC4x3/Properties/b/BoreholeCount_1DBeislK1CbfTPnPGztE29/DocProperty.xml
  IFC4x3/Properties/b/BoreholeCount_1DBeislK1CbfTPnPGztE29/Documentation.md
  IFC4x3/Properties/b/BoreholeSpacing_3zHZ8zixv0VPAwab6YkHPN/DocProperty.xml
  IFC4x3/Properties/b/BoreholeSpacing_3zHZ8zixv0VPAwab6YkHPN/Documentation.md
  IFC4x3/Properties/d/DewateringMethod_2oFu7BguH14vxA2DX0JNDX/DocProperty.xml
  IFC4x3/Properties/d/DewateringMethod_2oFu7BguH14vxA2DX0JNDX/Documentation.md
  IFC4x3/Properties/s/StaticDischargeHead_0BrAnLHer7kPgv2nOUi7ob/DocProperty.xml
  IFC4x3/Properties/s/StaticDischargeHead_0BrAnLHer7kPgv2nOUi7ob/Documentation.md
  IFC4x3/Properties/s/StaticSuctionLift_1nUwk$OBT5O9pgD19FbFDm/DocProperty.xml
  IFC4x3/Properties/s/StaticSuctionLift_1nUwk$OBT5O9pgD19FbFDm/Documentation.md
  IFC4x3/PropertyConstants/d/DEEPWELL_2PwZhTskj2V8OfGWvFYuKw.xml
  IFC4x3/PropertyConstants/e/EDUCTORWELLS_1LL9tl1_j8B8nYd0uYcCEf.xml
  IFC4x3/PropertyConstants/s/SUMPPUMP_1DUgjYAoH4Gh7jVsG9H47C.xml
  IFC4x3/PropertyConstants/v/VACUUMWELLPOINTS_1Ut4uPtD93cPyjtvmBw5Sq.xml
  IFC4x3/PropertyConstants/w/WELLPOINT_3HsrVdJYjAsOoHKTQjQhpE.xml
  IFC4x3/PropertyEnumerations/d/PEnum_DewateringMethod.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_ImprovedGroundTypeDewatered/DocPropertySet.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_ImprovedGroundTypeDewatered/Documentation.md
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcImprovedGroundTypeEnum/DocEnumeration.xml
Labels: EXPRESS, IFC Tunnel, properties, BucketB

#841 correct IfcCorrectLocalPlacement function
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricConstraintResource/Functions/IfcCorrectLocalPlacement/Documentation.md
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricConstraintResource/Functions/IfcCorrectLocalPlacement/Expression.txt
Labels: EXPRESS

#843 adding CorrectLinearPlacement rule and description
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricConstraintResource/Entities/IfcLinearPlacement/DocEntity.xml
Labels: EXPRESS

#847 update voxel grid
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
Labels: EXPRESS

#848 PredefinedType reconciliation
  IFC4x3/Constants/d/DILATIONTRACK_0xfV_G8V13XQP1c$$BAZ$d.xml
  IFC4x3/Constants/s/SUBSTRUCTURE_25ItrbLNDCyQmL1$9MUepS.xml
  IFC4x3/Constants/t/TRACK_2DsUX4_wH2ohPCYUU$_DdI.xml
  IFC4x3/Constants/t/TURNOUTTRACK_3q3hz8JJP2kvVx2xR83f$5.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcBridge/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcBridgePart/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcFacilityPartCommon/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcVirtualElement/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcPortsAndWaterwaysDomain/Entities/IfcMarineFacility/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcPortsAndWaterwaysDomain/Entities/IfcMarinePart/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/Entities/IfcRailway/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/Entities/IfcRailwayPart/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRailDomain/Types/IfcRailwayPartTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRoadDomain/Entities/IfcRoad/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcRoadDomain/Entities/IfcRoadPart/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralAnalysisDomain/Entities/IfcStructuralAnalysisModel/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralElementsDomain/Entities/IfcSurfaceFeature/DocEntity.xml
  IFC4x3/Sections/Domain specific data schemas/Schemas/IfcStructuralElementsDomain/Entities/IfcVoidingFeature/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedFacilitiesElements/Entities/IfcFurniture/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedFacilitiesElements/Entities/IfcFurnitureType/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedFacilitiesElements/Entities/IfcSystemFurnitureElement/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedFacilitiesElements/Entities/IfcSystemFurnitureElementType/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcEarthworksCut/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcGeotechnicalStratum/DocEntity.xml
Labels: EXPRESS, reconcile

#849 Feature/optional array entries
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcIntegerVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcLabelVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcLogicalVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcRealVoxelData/DocEntity.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Entities/IfcVectorVoxelData/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometryResource/Functions/IfcListToExpandedArray/Expression.txt
Labels: EXPRESS

#851 ifcsectionedsurface.areaprofiletypes
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcSectionedSurface/DocEntity.xml
Labels: EXPRESS

#828 EX-SU-Pset_ElementAssemblyTypeRing & PSet_ArchElementTypeSegment
  IFC4x3/Constants/r/RING_0Bdw3B_nLF5xDn3_ikasMK.xml
  IFC4x3/Properties/l/LongitudinalJointConnections_0euxSzkhDAcfFPu$B$85Tb/DocProperty.xml
  IFC4x3/Properties/l/LongitudinalJointConnections_0euxSzkhDAcfFPu$B$85Tb/Documentation.md
  IFC4x3/Properties/l/LongitudinalJointType_043Isdhjv28ObjidKJA1er/DocProperty.xml
  IFC4x3/Properties/l/LongitudinalJointType_043Isdhjv28ObjidKJA1er/Documentation.md
  IFC4x3/Properties/m/Mountings_0mEOFrv8f3iR74VNumT8C2/DocProperty.xml
  IFC4x3/Properties/m/Mountings_0mEOFrv8f3iR74VNumT8C2/Documentation.md
  IFC4x3/Properties/r/RadialJointConnections_0oSYw0FNv6_xS_Fj6q_a9u/DocProperty.xml
  IFC4x3/Properties/r/RadialJointConnections_0oSYw0FNv6_xS_Fj6q_a9u/Documentation.md
  IFC4x3/Properties/r/RadialJointType_0Td7PHpJb2JQKm0I0w16ak/DocProperty.xml
  IFC4x3/Properties/r/RadialJointType_0Td7PHpJb2JQKm0I0w16ak/Documentation.md
  IFC4x3/Properties/r/RingType_19mOtbL$f8jRVRPXORtt$x/DocProperty.xml
  IFC4x3/Properties/r/RingType_19mOtbL$f8jRVRPXORtt$x/Documentation.md
  IFC4x3/PropertyConstants/c/CONCAVE_CONVEX_2ce5d2r5bFARqt407gptBA.xml
  IFC4x3/PropertyConstants/c/CONICAL_26RuieLNzFzgzGBCuts7cB.xml
  IFC4x3/PropertyConstants/c/CONVEX_CONVEX_2aOB10Pv993OdO4W9RnUic.xml
  IFC4x3/PropertyConstants/f/FLAT_0UA$v62_D5rOGjxDe1TS9C.xml
  IFC4x3/PropertyConstants/h/HEXAGONAL_2Jr9$rap1CU8tgt$57FRl1.xml
  IFC4x3/PropertyConstants/i/INVERT_SEGMENT_WITH_SHOTCRETE_0ioCsK3H1CjgP5V2Oh9RYy.xml
  IFC4x3/PropertyConstants/p/PARALLEL_3lJJ0s6nr5eOwnkdiq2IaG.xml
  IFC4x3/PropertyConstants/p/PARALLEL_WITH_CORRECTIVE_RINGS_3CMdaJ0BDCQg7JquajrJyX.xml
  IFC4x3/PropertyConstants/s/SWISS_TÜBBING_3vXlScVwfBgv5kMIoxKGRM.xml
  IFC4x3/PropertyConstants/t/TONGUE_GROOVE_3$cx1SJoTDuQBpEoCXtIYt.xml
  IFC4x3/PropertyConstants/u/UNIVERSAL_3Hj28uW759TQTfl6vNKcMr.xml
  IFC4x3/PropertyEnumerations/r/PEnum_RingType.xml
  IFC4x3/PropertyEnumerations/s/PEnum_SegmentJointType.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/PropertySets/Pset_ElementAssemblyTypeRing/DocPropertySet.xml
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/PropertySets/Pset_ElementAssemblyTypeRing/Documentation.md
  IFC4x3/Sections/Core data schemas/Schemas/IfcProductExtension/Types/IfcElementAssemblyTypeEnum/DocEnumeration.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/PropertySets/Pset_ArchElementTypeSegment/DocPropertySet.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/PropertySets/Pset_ArchElementTypeSegment/Documentation.md
Labels: EXPRESS, IFC Tunnel, properties, BucketB

#858 THK-IfcBuildingSystem WR
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedBldgElements/Entities/IfcBuildingSystem/DocEntity.xml
Labels: EXPRESS

#855 Fix ifc map conversion rules
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcRepresentationResource/Entities/IfcMapConversion/DocEntity.xml
Labels: EXPRESS

#857 inverse IfcProperty.PartOfMaterialOrProfileProperties to IfcExtendePoperties
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcPropertyResource/Entities/IfcProperty/DocEntity.xml
Labels: EXPRESS

#852 THK-IfcImprovedGround PDTs
  IFC4x3/Properties/s/StaticSuctionLift_1nUwk$OBT5O9pgD19FbFDm/DocProperty.xml
  IFC4x3/PropertyEnumerations/d/PEnum_DewateringMethod.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Entities/IfcImprovedGround/DocEntity.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/PropertySets/Pset_ImprovedGroundTypeDewatered/DocPropertySet.xml
  IFC4x3/Sections/Shared element data schemas/Schemas/IfcSharedInfrastructureElements/Types/IfcImprovedGroundTypeEnum/DocEnumeration.xml
Labels: bug, EXPRESS

#859 Feature/ifc voxel grid ifc tessellated item
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcTessellatedFaceSet/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcTessellatedItem/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcGeometricModelResource/Entities/IfcVoxelGrid/DocEntity.xml
  IFC4x3/Sections/Resource definition data schemas/Schemas/IfcPresentationAppearanceResource/Entities/IfcIndexedColourMap/DocEntity.xml
Labels: EXPRESS
